from __future__ import annotations

import os
from typing import Optional, Literal

PathLikeStr = str | os.PathLike[str]

class CommitInfo:
    id: str
    summary: Optional[str]
    author: str
    email: Optional[str]
    time: int
    offset_minutes: int

class RewriteResult:
    old_to_new: dict[str, str]
    updated_refs: dict[str, str]
    warnings: list[str]
    backup_root: str | None

class DiffStat:
    files_changed: int
    insertions: int
    deletions: int
    paths: list[str]

class RepoSummary:
    path: str
    head: str | None
    branch: str | None
    commits: int
    branches: int
    tags: int
    remotes: int
    authors: int
    files: int
    size_kb: int
    is_dirty: bool
    last_commit_time: int | None

class Repo:
    def head(self) -> Optional[CommitInfo]: ...
    def rev_parse(self, spec: str) -> str: ...
    def reword(self, commit_id: str, new_message: str) -> RewriteResult: ...
    def summary(self) -> RepoSummary: ...
    def render_refs(self, local: bool = True, remote: bool = False, tags: bool = True, max_width: int | None = None, color: bool = False) -> str: ...
    def render_log(self, rev: str, max_commits: int = 200, decorate: bool = True, graph: bool = True, max_width: int | None = None, color: bool = False) -> str: ...
    def log_graph(self, refs: list[str] | None = None, max_commits: int = 400, decorate: bool = True, max_width: int | None = None, color: bool = True) -> str: ...
    # Aliases
    def refs_tui(self, local: bool = True, remote: bool = False, tags: bool = True, max_width: int | None = None, color: bool | Literal["auto"] = "auto") -> str: ...
    def log_tui(self, rev: str = "HEAD", max_commits: int = 200, decorate: bool = True, graph: bool = True, max_width: int | None = None, color: bool | Literal["auto"] = "auto") -> str: ...
    def diff_stat(self, a_spec: str, b_spec: str, paths: list[str] | None = None) -> DiffStat: ...
    def list_branches(self, local: bool = True, remote: bool = False) -> list[str]: ...
    def list_tags(self) -> list[str]: ...
    def current_branch(self) -> Optional[str]: ...
    def list_commits(self, max: Optional[int] = None) -> list[CommitInfo]: ...
    def create_backup_ref(self, prefix: str | None = None) -> str: ...
    def change_commit_message(self, commit_id: str, new_message: str) -> RewriteResult: ...
    def rewrite_author(self, commit_id: str, new_name: str, new_email: str, update_committer: bool = True) -> RewriteResult: ...
    def filter_commits(self, author: str | None = None, message_contains: str | None = None) -> RewriteResult: ...
    def remove_path(self, path_pattern: str) -> RewriteResult: ...
    def keep_path(self, glob_pattern: str) -> RewriteResult: ...
    def rebase_branch(self, branch: str, onto: str) -> RewriteResult: ...
    def squash_last(self, count: int, mode: str = "squash", message: str | None = None) -> RewriteResult: ...
    def merge_base(self, a_spec: str, b_spec: str) -> str | None: ...
    def is_ancestor(self, a_spec: str, b_spec: str) -> bool: ...
    def ahead_behind(self, a_spec: str, b_spec: str) -> tuple[int, int]: ...

def open_repo(path: PathLikeStr) -> Repo: ...

def summary(repo: Repo | PathLikeStr) -> RepoSummary: ...
def refs_tui(repo: Repo | PathLikeStr, local: bool = True, remote: bool = False, tags: bool = True, max_width: int | None = None, color: bool | Literal["auto"] = "auto") -> str: ...
def log_tui(repo: Repo | PathLikeStr, rev: str = "HEAD", max_commits: int = 200, decorate: bool = True, graph: bool = True, max_width: int | None = None, color: bool | Literal["auto"] = "auto") -> str: ...
def log_graph(repo: Repo | PathLikeStr, refs: list[str] | None = None, max_commits: int = 400, decorate: bool = True, max_width: int | None = None, color: bool | Literal["auto"] = "auto") -> str: ...

__all__ = [
    "CommitInfo",
    "DiffStat",
    "RepoSummary",
    "Repo",
    "RewriteResult",
    "open_repo",
    "summary",
    "refs_tui",
    "log_tui",
    "log_graph",
]
