from __future__ import annotations

import os
from typing import Optional

PathLikeStr = str | os.PathLike[str]

class CommitInfo:
    id: str
    summary: Optional[str]
    author: str
    email: Optional[str]
    time: int
    offset_minutes: int

class RewriteResult:
    old_to_new: dict[str, str]
    updated_refs: dict[str, str]
    warnings: list[str]
    backup_root: str | None

class Repo:
    def head(self) -> Optional[CommitInfo]: ...
    def rev_parse(self, spec: str) -> str: ...
    def reword(self, commit_id: str, new_message: str) -> RewriteResult: ...
    def list_commits(self, max: Optional[int] = None) -> list[CommitInfo]: ...
    def create_backup_ref(self, prefix: str | None = None) -> str: ...
    def change_commit_message(self, commit_id: str, new_message: str) -> RewriteResult: ...
    def reword(repo: Repo | PathLikeStr, commit_id: str, new_message: str) -> RewriteResult: ...
    def rewrite_author(self, commit_id: str, new_name: str, new_email: str, update_committer: bool = True) -> RewriteResult: ...
    def filter_commits(self, author: str | None = None, message_contains: str | None = None) -> RewriteResult: ...
    def remove_path(self, path_pattern: str) -> RewriteResult: ...
    def keep_path(self, glob_pattern: str) -> RewriteResult: ...
    def rebase_branch(self, branch: str, onto: str) -> RewriteResult: ...
    def squash_last(self, count: int, mode: str = "squash", message: str | None = None) -> RewriteResult: ...

def open_repo(path: PathLikeStr) -> Repo: ...
def create_backup_ref(repo: Repo | PathLikeStr, prefix: str | None = None) -> str: ...

def head(repo: Repo | PathLikeStr) -> Optional[CommitInfo]: ...
def rev_parse(repo: Repo | PathLikeStr, spec: str) -> str: ...
def list_commits(repo: Repo | PathLikeStr, max: Optional[int] = None) -> list[CommitInfo]: ...
def change_commit_message(repo: Repo | PathLikeStr, commit_id: str, new_message: str) -> RewriteResult: ...
def reword(repo: Repo | PathLikeStr, commit_id: str, new_message: str) -> RewriteResult: ...
def rewrite_author(repo: Repo | PathLikeStr, commit_id: str, new_name: str, new_email: str, update_committer: bool = True) -> RewriteResult: ...
def filter_commits(repo: Repo | PathLikeStr, author: str | None = None, message_contains: str | None = None) -> RewriteResult: ...
def remove_path(repo: Repo | PathLikeStr, path_pattern: str) -> RewriteResult: ...
def keep_path(repo: Repo | PathLikeStr, glob_pattern: str) -> RewriteResult: ...
def rebase_branch(repo: Repo | PathLikeStr, branch: str, onto: str) -> RewriteResult: ...
def squash_last(repo: Repo | PathLikeStr, count: int, mode: str = "squash", message: str | None = None) -> RewriteResult: ...

__all__ = [
    "CommitInfo",
    "Repo",
    "RewriteResult",
    "open_repo",
    "head",
    "rev_parse",
    "reword",
    "list_commits",
    "change_commit_message",
    "rewrite_author",
    "filter_commits",
    "remove_path",
    "keep_path",
    "rebase_branch",
    "squash_last",
]
