"""
Helpers to generate sample git repositories for pygitx demos/tests.
"""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

GENERATED_MODULE = Path(__file__).with_name("generated_repo.py")


def run(cmd: list[str], cwd: Path) -> None:
    subprocess.run(cmd, cwd=cwd, check=True)


def generate_repo(dest: Path | None = None, persist: bool = True) -> Path:
    """Create a sample repo; optionally persist its path for later reuse."""
    repo_path = dest or Path(tempfile.mkdtemp(prefix="pygitx-demo-"))
    repo_path.mkdir(parents=True, exist_ok=True)

    run(["git", "init", "-q"], cwd=repo_path)
    run(["git", "config", "user.name", "PyGitX"], cwd=repo_path)
    run(["git", "config", "user.email", "pygitx@example.com"], cwd=repo_path)

    # Commit 1 on main
    (repo_path / "file.txt").write_text("hello\n")
    run(["git", "add", "file.txt"], cwd=repo_path)
    run(["git", "commit", "-m", "base1"], cwd=repo_path)

    # Commit 2 on main
    (repo_path / "file.txt").write_text("hello base2\n")
    run(["git", "add", "file.txt"], cwd=repo_path)
    run(["git", "commit", "-m", "base2"], cwd=repo_path)

    # Create feature branch from base1
    run(["git", "branch", "feature", "HEAD~1"], cwd=repo_path)
    run(["git", "checkout", "feature"], cwd=repo_path)

    # Commit on feature (divergent content)
    (repo_path / "feature.txt").write_text("feature work\n")
    run(["git", "add", "feature.txt"], cwd=repo_path)
    run(["git", "commit", "-m", "feature1"], cwd=repo_path)

    # Add another commit on main to make rebase meaningful
    run(["git", "checkout", "main"], cwd=repo_path)
    (repo_path / "file.txt").write_text("hello base3\n")
    run(["git", "add", "file.txt"], cwd=repo_path)
    run(["git", "commit", "-m", "base3"], cwd=repo_path)

    if persist:
        persist_repo_path(repo_path)
    return repo_path


def persist_repo_path(path: Path) -> None:
    content = (
        "# Auto-generated by repo_factory.generate_repo\n"
        "from pathlib import Path\n"
        f'REPO_PATH = Path(r"{path}")\n'
    )
    GENERATED_MODULE.write_text(content)


def load_repo_path() -> Path | None:
    """Return the last generated repo path if recorded, else None."""
    if not GENERATED_MODULE.exists():
        return None
    try:
        import importlib.util

        spec = importlib.util.spec_from_file_location("generated_repo", GENERATED_MODULE)
        if spec and spec.loader:
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            return Path(getattr(module, "REPO_PATH"))
    except Exception:
        return None
    return None


def clean_repo() -> None:
    """Remove the generated repo path (if recorded) and delete the directory."""
    path = load_repo_path()
    if path and path.exists():
        try:
            import shutil

            shutil.rmtree(path, ignore_errors=True)
        except Exception:
            pass
    if GENERATED_MODULE.exists():
        try:
            GENERATED_MODULE.unlink()
        except Exception:
            pass
