"""
Helpers to generate sample git repositories for pygitx demos/tests.

This clones a fixed upstream repository (git2-rs) and layers a linear demo
branch with fixtures for filtering (secrets/, WIP commits, etc.). The demo
branch is created as an orphan to keep history merge-free for rewriting APIs.
Requires network access to clone the upstream repo.
"""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path
import shutil

GENERATED_MODULE = Path(__file__).with_name("generated_repo.py")
GIT_TEMPLATE_URL = "https://github.com/rust-lang/git2-rs.git"


def run(cmd: list[str], cwd: Path) -> None:
    subprocess.run(cmd, cwd=cwd, check=True)


def run_capture(cmd: list[str], cwd: Path) -> str:
    return subprocess.check_output(cmd, cwd=cwd, text=True).strip()


def generate_repo(
    dest: Path | None = None,
    persist: bool = True,
    branch_name: str = "pygitx-demo",
) -> Path:
    """
    Clone a fixed template repo (git2-rs) and layer an orphan demo branch with
    linear history suitable for rewrite/filter demonstrations.
    """
    repo_path = dest or Path(tempfile.mkdtemp(prefix="pygitx-demo-"))
    repo_path.mkdir(parents=True, exist_ok=True)

    # Clone without hardlinks to keep demo repos self-contained.
    run(
        ["git", "clone", "--quiet", "--no-hardlinks", GIT_TEMPLATE_URL, str(repo_path)],
        cwd=repo_path.parent,
    )

    # Ensure predictable identity for demo commits.
    run(["git", "config", "user.name", "PyGitX"], cwd=repo_path)
    run(["git", "config", "user.email", "pygitx@example.com"], cwd=repo_path)

    create_orphan_demo_branch(repo_path, branch_name)

    if persist:
        persist_repo_path(repo_path)
    return repo_path


def create_orphan_demo_branch(repo_path: Path, branch_name: str) -> None:
    # Switch to an orphan branch so history is linear and isolated from upstream merges.
    run(["git", "checkout", "--orphan", branch_name], cwd=repo_path)
    wipe_workdir(repo_path)

    # Commit 1: base file
    (repo_path / "file.txt").write_text("hello demo\n")
    run(["git", "add", "file.txt"], cwd=repo_path)
    run(["git", "commit", "-m", "demo: base"], cwd=repo_path)

    # Commit 2: add secrets/logs/feature fixtures (force add if ignored).
    (repo_path / "secrets").mkdir(parents=True, exist_ok=True)
    (repo_path / "logs").mkdir(parents=True, exist_ok=True)
    (repo_path / "secrets" / "token.txt").write_text("super-secret\n")
    (repo_path / "logs" / "debug.log").write_text("debug trace\n")
    (repo_path / "feature.txt").write_text("feature work\n")
    run(["git", "add", "-f", "secrets/token.txt", "logs/debug.log", "feature.txt"], cwd=repo_path)
    run(["git", "commit", "-m", "demo: add fixtures (secrets/logs/feature)"], cwd=repo_path)

    # Commit 3: WIP change (for message/author filtering).
    (repo_path / "feature.txt").write_text("WIP changes\n")
    run(["git", "add", "feature.txt"], cwd=repo_path)
    run(
        [
            "git",
            "commit",
            "-m",
            "WIP: temp feature",
            "--author",
            "Jiucheng <jiucheng@example.com>",
        ],
        cwd=repo_path,
    )

    # Commit 4: cleanup removing secret (for path filtering).
    run(["git", "rm", "-f", "secrets/token.txt"], cwd=repo_path)
    run(["git", "commit", "-m", "cleanup: remove secret"], cwd=repo_path)

    # Stay on the demo branch.
    run(["git", "checkout", branch_name], cwd=repo_path)


def persist_repo_path(path: Path) -> None:
    content = (
        "# Auto-generated by repo_factory.generate_repo\n"
        "from pathlib import Path\n"
        f'REPO_PATH = Path(r"{path}")\n'
    )
    GENERATED_MODULE.write_text(content)


def load_repo_path() -> Path | None:
    """Return the last generated repo path if recorded, else None."""
    if not GENERATED_MODULE.exists():
        return None
    try:
        import importlib.util

        spec = importlib.util.spec_from_file_location("generated_repo", GENERATED_MODULE)
        if spec and spec.loader:
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            return Path(getattr(module, "REPO_PATH"))
    except Exception:
        return None
    return None


def clean_repo() -> None:
    """Remove the generated repo path (if recorded) and delete the directory."""
    path = load_repo_path()
    if path and path.exists():
        try:
            import shutil

            shutil.rmtree(path, ignore_errors=True)
        except Exception:
            pass
    if GENERATED_MODULE.exists():
        try:
            GENERATED_MODULE.unlink()
        except Exception:
            pass


def wipe_workdir(root: Path) -> None:
    """Remove all files except the .git directory."""
    for entry in root.iterdir():
        if entry.name == ".git":
            continue
        if entry.is_dir():
            shutil.rmtree(entry, ignore_errors=True)
        else:
            entry.unlink(missing_ok=True)
